---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
  # Local hooks for Lua
-   repo: local
    hooks:
      - id: luacheck
        name: Lua Check
        entry: luacheck
        language: system  # Uses the system's Lua environment
        types: [lua]
        files: \.lua$
        args: [--codes]  # Optional: customize luacheck arguments

      - id: stylua
        name: Stylua Formatter
        entry: stylua
        language: system  # Uses the system's environment
        types: [lua]
        files: \.lua$
