[repository]
name = "hyprlua"
authors = ["cacarico"]
commit_pins = [
    ["4b07770b9ef1cceb2e6f56d33538aaffb9186b9c", "14b2c603e71ca45e7e1e256e38f3905fd79c4031"],
    ["4b07770b9ef1cceb2e6f56d33538aaffb9186b9c", "9c5635d8c82df569f72b05191e07d2d789d9c947"],
]

[hyprlua]
description = "Lua 5.4 scripting support for Hyprland"
authors = ["cacarico"]
output = "build/libhyprlua.so"
build = [
    "cmake -B build -DCMAKE_BUILD_TYPE=Release",
    "cmake --build build -j$(nproc)",
]
