[repository]
name = "hyprlua"
authors = ["cacarico"]

[hyprlua]
description = "Lua 5.4 scripting support for Hyprland"
authors = ["cacarico"]
output = "build/libhyprlua.so"
build = [
    "cmake -B build -DCMAKE_BUILD_TYPE=Release",
    "cmake --build build -j$(nproc)",
]
